# Generated by Django 3.2.15 on 2022-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('publication', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(max_length=10000)),
                ('embed', models.TextField(blank=True, max_length=10000)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('show', models.BooleanField(blank=True, default=True)),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('org', models.CharField(blank=True, max_length=50, null=True)),
                ('accomplishments', models.TextField(max_length=100000)),
                ('current', models.BooleanField(blank=True, default=False)),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
        ),
    ]
