# Generated by Django 3.2.15 on 2022-11-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_image_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ManyToManyField(to='core.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
