# Generated by Django 3.2.15 on 2022-11-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
    ]
