# Generated by Django 3.2.15 on 2022-11-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='picture',
            new_name='pictures',
        ),
    ]
