# Generated by Django 3.2.15 on 2022-11-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_picture_project_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
